language: java
before_install:
- rm -rf target
script: "mvn verify -B"
deploy:
  provider: releases
  api_key:
    secure: "SenKfpDrABJJ9sGCQCE27/odgxJdYNztOPf7uJ3oe0IGYydIpCC9p3dRsWGZVL1NUTAl9+tyMi+bDJGPU4Dg8L/UIy3Xkjtjxz+a2DWcBa3NbiTRpgvN9oUtefLpg/mmjISLPnNrXC/dD8+UAbnVpDXvbaf1oy5kTBwHNgOrmYI/Z9D698OXuyM2rFt0RfJ+ku0blKTKZUJVGGz5s+oK+GqUhsiVFaDzTafron+2HSuzt9+PIZen5aECKMyzB7xXmiziiN9THPtKGacbUopvM1C0SWzacBDT7ouQCu/aYWcx6gDjq0e4uqL2LYyx+JkhiL7Nigk8bSOjZ3YDcyAnEAeybdJY8twLmzTgERGsqzLyAN3URDjY2hWaTz+h3vLrOlKu9/nsujCReU9dXli6zYa3ZCyFPnhrrDOwidcMx7QMFxWobwZ/p8P78IMnA9wa8rIaPuzPzc1uSVd0r2JE4mJH1jzOennQUbYR+6AGERyzu5H98OyEt6OXbZVOT8k3wzsWURaO/ePNK+xzxQzAsFgIe/tsBfa5GoN/RjnvAmnxWCX/TVbqK4a5PVIDLEivhvaCdBoqIf1R5k9et6z0sDjo90rh9ILH7R3LUXkwmToEPB3BBBBWf4foEuwHvjbxr91Y8lDnB3wSLrfICcbuTEiS++24TkANwfL/UQpFXRA="
  file: "target/jmeter-sshmon-*.jar"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: tilln/jmeter-sshmon
    tags: true
